volpes-master/Natale/Models/RequestsKids.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Natale.Classes;

namespace Natale.Models
{
    public class RequestsKids
    {
        public List <RequestKid> EntityList { get; set; }
        public List<ToyKid> ToyList { get; set; }
        
        
    }
}

volpes-master/Natale/Models/Toys.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Natale.Classes;
namespace Natale.Models
{
    public class Toys
    {
        public List<Toy> EntityList { get; set; }
    }
}

volpes-master/Natale/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Natale.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

volpes-master/Natale/Controllers/RequestKidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Natale.Classes;
using Natale.Models;
using NataleMongoDB = Natale.Classes.MongoDB;

namespace Natale.Controllers
{
    public class RequestKidController : Controller
    {
        // GET: RequestKid
        public ActionResult Index()
        {
            NataleMongoDB db = new NataleMongoDB();
            var requests_kids = db.GetAllRequestKid();
            RequestsKids model = new RequestsKids();
            model.EntityList = requests_kids.ToList();
            return View(model);
        }

        public ActionResult Details(string id)
        {
            NataleMongoDB db = new NataleMongoDB();
            var request_kid = db.GetRequest(id);
            RequestsKids model = new RequestsKids();
            ViewBag.Id = request_kid.ID;
            ViewBag.KidName = request_kid.KidName;
            ViewBag.Date = request_kid.Date.ToString("dd-MMM-yyyy");
            switch (request_kid.Status.ToString())
            {
                case "0":
                    ViewBag.Status = "In Progress";
                    break;
                case "1":
                    ViewBag.Status = "Available";
                    break;
                case "2":
                    ViewBag.Status = "Done";
                    break;

                default:
                    break;
            }

            model.ToyList = request_kid.ToyKids;
            
            return View(model);
        }

        
        public ActionResult Edit(string id)
        {
            NataleMongoDB db = new NataleMongoDB();
            var request_kid = db.GetRequest(id);
            //utile per estrarre tutti i giochi richiesto dal bambino
            RequestsKids modelToy = new RequestsKids();
            modelToy.ToyList = request_kid.ToyKids;
            Toy toy = new Toy();
            //utile per passare alla view lo stato dell ordine
            RequestKid model = new RequestKid();
            model.Status = request_kid.Status;
            return View(model);
        }

        public ActionResult Save(int status,string id)
        {
            if (string.IsNullOrWhiteSpace(status.ToString()))
            {
                throw new MissingFieldException("name cannot be null");
            }
            bool result;
            NataleMongoDB db = new NataleMongoDB();
            var request_kid = db.GetRequest(id);
            RequestsKids modelToy = new RequestsKids();
            modelToy.ToyList = request_kid.ToyKids;
            Toy toy = new Toy();
            var query = modelToy.ToyList.GroupBy(x => x)
                                .Select(y => new { Element = y.Key, Counter = y.Count() })
                                .ToList();
            foreach (var toyRequest in query)
            {
                toy = db.GetToy(toyRequest.Element.ToyName);
                if (toy.Amount <= toyRequest.Counter)
                {
                    ModelState.AddModelError("", "Order no Avaible");
                    return RedirectToAction("Details", id);
                }
            }

            if (string.IsNullOrWhiteSpace(id))
            {
                RequestKid requestkid = new RequestKid();
                
            }
            
            result = db.UpdateStatus(new RequestKid
            {
                ID = id,
                Status = status
            });
            

            foreach (var toyRequest in modelToy.ToyList)
            {
                
                toy = db.GetToy(toyRequest.ToyName);
                result = db.UpdateAmountToy(toy);
                if (toy.Amount == 0)
                {
                    db.RemoveToy(toy.ID);
                }
            }
            
            return RedirectToAction("Index", new { result = result });
        }
    }
}

volpes-master/Natale/Controllers/ToysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Natale.Classes;
using Natale.Models;
using NataleMongoDB = Natale.Classes.MongoDB;

namespace Natale.Controllers
{
    public class ToysController : Controller
    {
        // GET: Toys
        public ActionResult Index()
        {
            NataleMongoDB db = new NataleMongoDB();
            var toys = db.GetAllToys();
            Toys model = new Toys();
            model.EntityList = toys.ToList();
            
            return View(model);
        }
    }
}

volpes-master/Natale/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Natale.Classes;
using System.Security.Cryptography;
using NataleMongoDB = Natale.Classes.MongoDB;
using System.Text;

namespace Natale.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Login()
        {
            return View();
        }

        string Encrypt(string text)
        {
            byte[] data = Encoding.UTF8.GetBytes(text);
            byte[] resultHash;
            SHA512 shaM = new SHA512Managed();
            resultHash = shaM.ComputeHash(data);
            StringBuilder result = new StringBuilder();
            for (int i = 0; i < resultHash.Length; i++)
            {
                result.Append(resultHash[i].ToString("X2"));
            }
            return result.ToString().ToLower();
        }
        [HttpPost]
        public ActionResult Login(User user)
        {
            user.Password = Encrypt(user.Password);
            NataleMongoDB db = new NataleMongoDB();
            var account = db.GetUser(user);
            if (account != null)
            {
                Session["Email"] = account.Email.ToString();
                Session["ID"] = account.ID.ToString();
                Session["ScreenName"] = account.ScreenName.ToString();
                Session["IsAdmin"] = account.isAdmin.ToString();
                return RedirectToAction($"../Home");
            }
            else
            {
                ModelState.AddModelError("", "Email or Password Error");
                
            }
            return View();
        }

        public ActionResult Logout()
        {
            if (Session["ID"] != null)
            {
                Session.Clear();
                return RedirectToAction("Logout");
            }
            return View();
        }

    }
}

volpes-master/Natale/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

volpes-master/Natale/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

volpes-master/Natale/Views/Home/DashboardUser.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "UserDashBoard";
}
<fieldset>
    <legend>User DashBoard</legend>
    @if (Session["ScreenName"] != null)
    {
        <text>Welcome @Session["ScreenName"].ToString()</text>
    }
</fieldset>

}

volpes-master/Natale/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

volpes-master/Natale/Views/RequestKid/Details.cshtml
@using Natale.Models
@{
    ViewBag.Title = "Details";
}
@model RequestsKids
@using Natale.Classes
<h2 style="text-align:center" ;>Transaction Details</h2>
<div>
    <h4>Requests Kid</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @ViewBag.Status
            
                @Html.ActionLink(" Edit", "Edit", new { id = @ViewBag.Id, status = @ViewBag.Status }, new { @class = "btn btn-default glyphicon glyphicon-pencil" })
            
        </dt>
        <dd>
            @ViewBag.KidName
        </dd>
        <dt>
            @ViewBag.Date
        </dt>
        Toys
        @foreach (var toys in Model.ToyList)
        {
            <dd>
                
                @toys.ToyName
            </dd>
        }
        
    </dl>
</div>

@Html.ActionLink(" Back", "Index", null, new { @class = "btn btn-primary glyphicon glyphicon-circle-arrow-left" })

volpes-master/Natale/Views/RequestKid/Edit.cshtml
@model Natale.Classes.RequestKid
@{
    ViewBag.Title = "Edit";
}
<h2 style="text-align:center;">Edit Request Status: @Model.KidName</h2>
@using (Html.BeginForm("Save", "RequestKid"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Payment Method</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.ID)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}
<div>
    @Html.ActionLink(" Back", "Index", null, new { @class = "btn btn-primary glyphicon glyphicon-circle-arrow-left" })
</div>

volpes-master/Natale/Views/RequestKid/Index.cshtml
@using Natale.Models
@{
    ViewBag.Title = " Request Toys Kids";
}
@model RequestsKids
    
<div class="row">
    <div class="col-xs-8">
        <h2 style="text-align:center;">Toys</h2>
    </div>
</div>

@if (Session["ScreenName"].ToString() == "FabulousZiggy")
{
    <table class="table">
        <thead>
            <tr>
                <th>Status</th>
                <th>Date</th>
                <th>Kid</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var request in Model.EntityList)
            {
                var colorAlert = "";
                var status = "";
                switch (request.Status)
                {
                    case 0:
                        status = "In Progress";
                        colorAlert = "alert-danger";
                        break;
                    case 1:
                        status = "Available";
                        colorAlert = "alert-warning";
                        break;
                    case 2:
                        status = "Done";
                        colorAlert = "alert-danger";
                        break;
                    default:
                        break;
                }
                <tr class=@colorAlert>
                    
                    <td>
                        @Html.DisplayName(status)
                    </td>
                    

                    <td>
                        @Html.ActionLink(request.Date.ToString("dd-MMM-yyyy"), "Details", new { id = request.ID })
                    </td>
                    <td>
                        @Html.ActionLink(request.KidName, "Details", new { id = request.ID })
                    </td>
                    <td>

                    </td>


                    
                </tr>
            }
        </tbody>
    </table>
}
else
{

    <table class="table">
        <thead>
            <tr>
                <th>Status</th>
                <th>Date</th>
                <th>Kid</th>
                <th>Price Tot</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var request in Model.EntityList)
            {
                var colorAlert = "";
                var status = "";
                switch (request.Status)
                {
                    case 0:
                        status = "In Progress";
                        colorAlert = "alert-danger";
                        break;
                    case 1:
                        status = "Available";
                        colorAlert = "alert-warning";
                        break;
                    case 2:
                        status = "Done";
                        colorAlert = "alert-success";
                        break;
                    default:
                        break;
                }
                <tr class=@colorAlert>

                    <td>
                        @Html.DisplayName(status)
                    </td>


                    <td>
                        @Html.DisplayName(request.Date.ToString("dd-MMM-yyyy"))
                    </td>
                    <td>
                        @Html.DisplayName(request.KidName)
                    </td>
                    <td></td>
                    @*<td>@Html.DisplayName(request.PriceRequest.ToString())</td>*@
                    @*<td>@ViewBag.s</td>*@
                </tr>
            }
        </tbody>
    </table>
}

volpes-master/Natale/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @if (Session["ID"] != null || Session["Email"] != null)
                {
                    @Html.ActionLink(Session["ScreenName"] + " Natale", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

                }
                else
                {
                    @Html.ActionLink("Natale", "", "Home", new { area = "" }, new { @class = "navbar-brand" })
                }
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["ID"] != null)
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Toys", "Index", "Toys")</li>
                        <li>@Html.ActionLink("Requests", "Index", "RequestKid")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Users")</li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Users")</li>
                    }
                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Natale Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/Scripts/CustomScripts/logInFacebook.js")
</body>
</html>

volpes-master/Natale/Views/Toys/Index.cshtml
@using Natale.Models
@{
    ViewBag.Title = "Toys";
}
@model Toys
<div class="row">
    <div class="col-xs-8">
        <h2 style="text-align:center;">Toys</h2>
    </div>
</div>
@foreach (var toys in Model.EntityList)
{
    <hr />
    <div class="row">
        <div class="col-xs-8">
            <h4>@toys.Name</h4>
        </div>
        <div class="col-xs-2">
            @toys.Amount
        </div>
        <div class="col-xs-2">
            @toys.Price
        </div>
    </div>
}

volpes-master/Natale/Views/Users/Login.cshtml
@model Natale.Classes.User
@{
    ViewBag.Title = "title";
}
@using (Html.BeginForm("Home"))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="row">
            <div class="col-xs-8">
                <h2 style="text-align:center;">Login</h2>
            </div>
            <div class="col-xs-4 form-group" style="margin-top:20px;">
                <input id="login" type="submit" value="Login" class=" btn btn-success" />
            </div>
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(Model => Model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(Model => Model.Email, new { htmlAttributes = new { @class = "form-control", id = "textName" } })
                @Html.ValidationMessageFor(Model => Model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(Model => Model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(Model => Model.Password, new { htmlAttributes = new { @class = "form-control", @type = "password", id = "textFBId" } })
                @Html.ValidationMessageFor(Model => Model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>

}

volpes-master/Natale/Views/Users/Logout.cshtml
@model Natale.Classes.User
@{
    ViewBag.Title = "title";
}
<h2 style="text-align:center;" h2>Log Out</h2>
<div class="row">
    <div class="col-xs-8">
        <h2 style="text-align:center;">Thank You for using My Natale App</h2>
    </div>
    <div class="col-xs-4 form-group" style="margin-top:20px;">
        @Html.ActionLink("Login", "Login", "Users", null, new { @class = "btn btn-success" })
    </div>
</div>